// Generated by the Blazor I18n Text compiler
namespace MyBlazorSite.Client.I18nText
{
    public partial class Navbar : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"About me"</summary>
        public string ABOUT_ME;

        /// <summary>"Contact me"</summary>
        public string CONTACT_ME;

        /// <summary>"Home"</summary>
        public string HOME;

        /// <summary>"My projects"</summary>
        public string MY_PROJECTS;

        /// <summary>"My site"</summary>
        public string TITLE;
    }
}
